---
- hosts: webserver
  become: yes
  gather_facts: yes
  tasks: 
    - include_tasks: myfilehandeling.yml

    - name: install apache2 on debian
      ansible.builtin.apt:
        name: "{{apache2_package}}" 
        state: present
      when: ansible_os_family == "Debian"

    - name: install httpd on redhat
      ansible.builtin.yum:
        name: "{{apache2_package}}" 
        state: present
      when: ansible_os_family == "RedHat"

    - name: install jenkins on debian
      ansible.builtin.get_url:
        url: "{{jenkins_package}}"
        dest: /home/maha/jenkins/
        mode: '0644'
        force_basic_auth: yes
      when: ansible_os_family == "Debian"
         
    - name: install jenkins on redhat
      ansible.builtin.get_url:
        url: "{{jenkins_package}}"
        dest: /home/maha/jenkins/
        mode: '0644'
        force_basic_auth: yes
      when: ansible_os_family == "RedHat"
