---
- hosts: webserver
  become: yes
  gather_facts: yes

  tasks:

    - name: Create a file on Debian
      ansible.builtin.file:
        path: /home/maha/newfile.txt
        state: touch
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Create a file on RedHat
      ansible.builtin.file:
        path: /home/maha/newfile.txt
        state: touch
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Copy the static file to Debian node
      ansible.builtin.copy:
        src: staticfile
        dest: /home/maha/
      when: ansible_os_family == "Debian"

    - name: Copy the static file to RedHat node
      ansible.builtin.copy:
        src: staticfile
        dest: /home/maha/
      when: ansible_os_family == "RedHat"

    - name: Copy the dynamic file to Debian node
      ansible.builtin.template:
        src: dynamic.j2
        dest: /var/www/html/index.html
      when: ansible_os_family == "Debian"

    - name: Copy the dynamic file to RedHat node
      ansible.builtin.template:
        src: dynamic.j2
        dest: /var/www/html/index.html
      when: ansible_os_family == "RedHat"

    - name: Download a file from internet on Debian
      ansible.builtin.get_url:
        url: https://www.magnific.com/free-photos-vectors/devops
        dest: /home/maha/
      when: ansible_os_family == "Debian"

    - name: Download a file from internet on RedHat
      ansible.builtin.get_url:
        url: https://www.magnific.com/free-photos-vectors/devops
        dest: /home/maha/
      when: ansible_os_family == "RedHat"