#SPDX-License-Identifier: MIT-0
---
# tasks file for mywebrole
- name: install apahe2 webserver 
  ansible.builtin.apt:
    name: "{{apache2var}}"
    state: present
  notify: restartapche2

- name: copy a static file 
  copy:
    src: template/staticfile.txt
    dest: /home/maha/staticfile.txt
    mode: '0644'

- name: create a new file
  file: 
    path: /home/maha/newfile.txt
    state: touch
    mode: '0644'

- name: create a new directory
  file: 
    path: /home/maha/dir01
    state: directory
    mode: '0644'

- name: copy a dynamic file
  template:
    src: dynamicfile.j2
    dest: /var/www/html/index.html
    mode: '0644'
